### **Importing the dependecies**

In [1]:
import numpy as np
import re
import pandas as pd
from textblob import TextBlob
from nltk.tokenize import sent_tokenize, word_tokenize

### **Removing HTML tags**

In [2]:
docs = '''
<div class="post">
  <h2>Welcome to <span style="color:blue;">My Blog</span></h2>
  <p>
    This is a <b>random</b> paragraph with <i>different</i> HTML tags.
    You might see <a href="#">links</a>, <u>underlined text</u>,
 ird tag <custom-tag>hello</custom-tag>.
  </p>
</div>

'''

In [3]:
def html_cleanp(data):
    p = re.compile(r'<*.?>')
    return p.sub('', data)

In [4]:
html_cleanp(docs)

'\n<div class="post\n  <hWelcome to <span style="color:blue;My Blog</spa</h\n  \n    This is a random</ paragraph with different</ HTML tags.\n    You might see <a href="#links</, underlined text</,\n ird tag <custom-tahello</custom-ta.\n  </\n</di\n\n'

### **Unicode Normalization**

In [5]:
emoji_Text = '''If you want, next we can:

🔥 apply greedy vs non-greedy regex on this

🧪 run your remove() function on it

🧠 compare regex vs BeautifulSoup output

Just tell me 😎'''

In [6]:
emoji_Text.encode('utf-8')

b'If you want, next we can:\n\n\xf0\x9f\x94\xa5 apply greedy vs non-greedy regex on this\n\n\xf0\x9f\xa7\xaa run your remove() function on it\n\n\xf0\x9f\xa7\xa0 compare regex vs BeautifulSoup output\n\nJust tell me \xf0\x9f\x98\x8e'

### **SPELLING CORRECTION**

In [7]:
# from textblob import TextBlob
text = 'Hi this is just a random person writinggg with the keyboarrd p to write 100 wpm tyyping speed, lets see he can do it or no, currently he is doing speling coreetion lets see he can do it or not.'

In [8]:
textblb = TextBlob(text)

textblb.correct()

TextBlob("I this is just a random person writing with the keyboard p to write 100 wm trying speed, lets see he can do it or no, currently he is doing spelling creation lets see he can do it or not.")

### **Tokenizing the sentence**

In [9]:
from nltk.tokenize import sent_tokenize, word_tokenize

In [10]:
sentene = 'hiiiiii this is a introvert typing some random shits i really dont know what to type so that i am typign randomly , i am learning NLP from CampusX, and i think he is. hiiiiii this is a introvert typing some random shits i really dont know what to type so that i am typign randomly , i am learning NLP from CampusX, and i think he is.hiiiiii this is a introvert typing some random shits i really dont know what to type so that i am typign randomly , i am learning NLP from CampusX, and i think he is. hiiiiii this is a .'

In [11]:
sents = sent_tokenize(sentene)
sents


['hiiiiii this is a introvert typing some random shits i really dont know what to type so that i am typign randomly , i am learning NLP from CampusX, and i think he is.',
 'hiiiiii this is a introvert typing some random shits i really dont know what to type so that i am typign randomly , i am learning NLP from CampusX, and i think he is.hiiiiii this is a introvert typing some random shits i really dont know what to type so that i am typign randomly , i am learning NLP from CampusX, and i think he is.',
 'hiiiiii this is a .']

#### **Word Tokenize**

In [12]:
for sent in sents:
    print(word_tokenize(sent))

['hiiiiii', 'this', 'is', 'a', 'introvert', 'typing', 'some', 'random', 'shits', 'i', 'really', 'dont', 'know', 'what', 'to', 'type', 'so', 'that', 'i', 'am', 'typign', 'randomly', ',', 'i', 'am', 'learning', 'NLP', 'from', 'CampusX', ',', 'and', 'i', 'think', 'he', 'is', '.']
['hiiiiii', 'this', 'is', 'a', 'introvert', 'typing', 'some', 'random', 'shits', 'i', 'really', 'dont', 'know', 'what', 'to', 'type', 'so', 'that', 'i', 'am', 'typign', 'randomly', ',', 'i', 'am', 'learning', 'NLP', 'from', 'CampusX', ',', 'and', 'i', 'think', 'he', 'is.hiiiiii', 'this', 'is', 'a', 'introvert', 'typing', 'some', 'random', 'shits', 'i', 'really', 'dont', 'know', 'what', 'to', 'type', 'so', 'that', 'i', 'am', 'typign', 'randomly', ',', 'i', 'am', 'learning', 'NLP', 'from', 'CampusX', ',', 'and', 'i', 'think', 'he', 'is', '.']
['hiiiiii', 'this', 'is', 'a', '.']


In [13]:
docss = '<p>hiiiiii this is a introvert typing some random shits i really dont know what to type so that i am typign randomly</p> hiiiiii this is a introvert typing some random shits i really dont know what to type so that i am typign randomly<p></p>hiiiiii this is a introvert typing some random shits i really dont know what to type so that i am typign randomly <p></p> <p>hiiiiii this is a introvert typing some random shits i really dont know what to type so that i am typign randomly</p>'

### **Lowercasing**

In [14]:
a = '''

Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maxime, iste cum? Repudiandae aliquam vero tempora nisi eum culpa! Vero dolore necessitatibus ipsa, blanditiis dolor tempore atque recusitae quam dolorem saepe repellat doloribus blanditiis, eos temporibus. Labore eum dicta totam cum ut eius obcaecati natus! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui debitis aliquid, magnam dolorem, fugiat numquam, mollitia porro commodi eaque omnis voluptates iste? Eum nihil a amet consectetur cum? Voluptate, esse!
    Ulltio repellendus laudantium obcaecati dolorem quisquam error libero officiis provident magnam. Recusandae est ducimus quae molestiae nemo quaerat ratione aliquam! Dolores culpa ut unde repellendus reiciendis pariatur soluta.
   
'''

In [15]:
print(a.lower())



lorem ipsum dolor, sit amet consectetur adipisicing elit. maxime, iste cum? repudiandae aliquam vero tempora nisi eum culpa! vero dolore necessitatibus ipsa, blanditiis dolor tempore atque recusitae quam dolorem saepe repellat doloribus blanditiis, eos temporibus. labore eum dicta totam cum ut eius obcaecati natus! lorem ipsum dolor, sit amet consectetur adipisicing elit. qui debitis aliquid, magnam dolorem, fugiat numquam, mollitia porro commodi eaque omnis voluptates iste? eum nihil a amet consectetur cum? voluptate, esse!
    ulltio repellendus laudantium obcaecati dolorem quisquam error libero officiis provident magnam. recusandae est ducimus quae molestiae nemo quaerat ratione aliquam! dolores culpa ut unde repellendus reiciendis pariatur soluta.
   



In [16]:
data = pd.read_csv(r"/mnt/c/Users/Subham Pathak/Desktop/AI/DEEP_LEARNING/notebooks/NLP/datasets/IMDB Dataset.csv")
data.head(10)

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive
5  Probably my all-time favorite movie, a story o...  positive
6  I sure would like to see a resurrection of a u...  positive
7  This show was an amazing, fresh & innovative i...  negative
8  Encouraged by the positive comments about this...  negative
9  If you like original gut wrenching laughter yo...  positive

In [17]:
data['review'][10].lower()

'phil the alien is one of those quirky films where the humour is based around the oddness of everything rather than actual punchlines.<br /><br />at first it was very odd and pretty funny but as the movie progressed i didn\'t find the jokes or oddness funny anymore.<br /><br />its a low budget film (thats never a problem in itself), there were some pretty interesting characters, but eventually i just lost interest.<br /><br />i imagine this film would appeal to a stoner who is currently partaking.<br /><br />for something similar but better try "brother from another planet"'

In [18]:
# if u want to lower all the data inside csv files

data['review'] = data['review'].str.lower()

In [19]:
a = '''
<p> Hiii this is Subham Pathak typinginto the keyboard , he really dont know anything...</p?
<p> iii thihits into the keyboard , he really dont know anything...</p>
<p> Hii this ime random shits into the keyboard , he really dont know anything...</p>
<p> Hiii this is Subham Pathak typing some random srd , he really dont know anything...</p>
<p> Hii tPathakme random shits into the, he really dont know anything...</p>

'''

In [20]:
import re
def process(datas):
    p = re.compile(r'<*.?>')
    return p.sub('', datas)


process(a)

'\n Hiii this is Subham Pathak typinginto the keyboard , he really dont know anything...</p?\n iii thihits into the keyboard , he really dont know anything...</\n Hii this ime random shits into the keyboard , he really dont know anything...</\n Hiii this is Subham Pathak typing some random srd , he really dont know anything...</\n Hii tPathakme random shits into the, he really dont know anything...</\n\n'

In [21]:
data['review'] = data['review'].apply(process)

### **Remove URL**

In [22]:
import re, string
text = '''
hiiiiii this is my link https://github.com/itzsubham2006?tab=overview&from=2026-01-01&to=2026-01-18 of github and my linkedin acc is https://www.linkedin.com/feed/.

'''

def remove_url(text):
    t = re.compile(r'https?://\S+|www\.\S+')
    return t.sub(r'', text)


remove_url(text)

'\nhiiiiii this is my link  of github and my linkedin acc is \n\n'

### **Remove Punctuations**

In [23]:
import string, time
exclude = string.punctuation
exclude

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [24]:
def punct(text):
    for char in exclude:
        text = text.replace(char, '')
        
    return text
        

In [25]:
punct("Hi, this is subham! pathakl'' typing. some andom $ shits`")

'Hi this is subham pathakl typing some andom  shits'

In [26]:
def make_translate(text):
    return text.translate(str.maketrans('', '', exclude))


start = time.time()
make_translate("Hi, this is subham! pathakl'' typing. some andom $ shits`")
time1 = time.time() - start

print(time1)

8.58306884765625e-05


### **REVISION**

In [27]:
text = '''
<p>Discover the <strong>latest trends</strong> in web development! 🚀<br>
Visit our <a href="https://www.example.com/news">official blog</a> for updates.<br>
Need help? Check out the <em>FAQ section</em> at <a href="https://support.example.com">support.example.com</a>.<br>
Stay inspired with daily <i>motivational quotes</i> from <a href="https://quotes.example.org/random">quotes.example.org</a>.</p>

<h3>Random Tip:</h3>
<ul>
  <li>Use <code>lorem5</code> in VS Code to generate <em>lorem ipsum</em> text instantly.</li>
  <li>Test links with <a href="https://validator.w3.org/">W3C Validator</a>.</li>
</ul>   

'''

In [28]:
# Removing the html tags
import re
def rmeove_html(data):
    p = re.compile(r'<*.?>')
    return p.sub(r'', data)

rmeove_html(text)

'\nDiscover the <stronlatest trends</stron in web development! 🚀<b\nVisit our <a href="https://www.example.com/newsofficial blog</ for updates.<b\nNeed help? Check out the <eFAQ section</e at <a href="https://support.example.comsupport.example.com</.<b\nStay inspired with daily motivational quotes</ from <a href="https://quotes.example.org/randomquotes.example.org</.</\n\n<hRandom Tip:</h\n<u\n  <lUse <codlorem5</cod in VS Code to generate <elorem ipsum</e text instantly.</l\n  <lTest links with <a href="https://validator.w3.org/W3C Validator</.</l\n</u   \n\n'

In [29]:
# Removing the emojis and all the these stuffs



In [30]:
# Spelling corerction

from textblob import TextBlob

test = TextBlob(text)

test.correct()

TextBlob("
<p>Discover the <strong>latest tends</strong> in web development! 🚀<br>
Visit our <a he="http://www.example.com/news">official blow</a> for updated.<br>
Need help? Check out the <em>FAQ section</em> at <a he="http://support.example.com">support.example.com</a>.<br>
Stay inspired with daily <i>motivation quotes</i> from <a he="http://quotes.example.org/random">quotes.example.org</a>.</p>

<he>Random Lip:</he>
<up>
  <li>Use <code>lore</code> in of Rode to generate <em>lore issue</em> text instantly.</li>
  <li>West links with <a he="http://validator.we.org/">W3C Validator</a>.</li>
</up>   

")

In [31]:
from nltk.tokenize import word_tokenize, sent_tokenize

tokenize_sentence = sent_tokenize(text)
print(tokenize_sentence)
print(len(tokenize_sentence))

['\n<p>Discover the <strong>latest trends</strong> in web development!', '🚀<br>\nVisit our <a href="https://www.example.com/news">official blog</a> for updates.<br>\nNeed help?', 'Check out the <em>FAQ section</em> at <a href="https://support.example.com">support.example.com</a>.<br>\nStay inspired with daily <i>motivational quotes</i> from <a href="https://quotes.example.org/random">quotes.example.org</a>.</p>\n\n<h3>Random Tip:</h3>\n<ul>\n  <li>Use <code>lorem5</code> in VS Code to generate <em>lorem ipsum</em> text instantly.</li>\n  <li>Test links with <a href="https://validator.w3.org/">W3C Validator</a>.</li>\n</ul>']
3


In [32]:
for word in tokenize_sentence:
    word_tokenize(word)
    print(word_tokenize(word))

['<', 'p', '>', 'Discover', 'the', '<', 'strong', '>', 'latest', 'trends', '<', '/strong', '>', 'in', 'web', 'development', '!']
['🚀', '<', 'br', '>', 'Visit', 'our', '<', 'a', 'href=', "''", 'https', ':', '//www.example.com/news', "''", '>', 'official', 'blog', '<', '/a', '>', 'for', 'updates.', '<', 'br', '>', 'Need', 'help', '?']
['Check', 'out', 'the', '<', 'em', '>', 'FAQ', 'section', '<', '/em', '>', 'at', '<', 'a', 'href=', "''", 'https', ':', '//support.example.com', "''", '>', 'support.example.com', '<', '/a', '>', '.', '<', 'br', '>', 'Stay', 'inspired', 'with', 'daily', '<', 'i', '>', 'motivational', 'quotes', '<', '/i', '>', 'from', '<', 'a', 'href=', "''", 'https', ':', '//quotes.example.org/random', "''", '>', 'quotes.example.org', '<', '/a', '>', '.', '<', '/p', '>', '<', 'h3', '>', 'Random', 'Tip', ':', '<', '/h3', '>', '<', 'ul', '>', '<', 'li', '>', 'Use', '<', 'code', '>', 'lorem5', '<', '/code', '>', 'in', 'VS', 'Code', 'to', 'generate', '<', 'em', '>', 'lorem', 'ip

In [33]:
import string

hehe = string.punctuation


In [34]:
def remove_punctuation(data):
    return data.translate(str.maketrans('','', hehe))


remove_punctuation(text)

'\npDiscover the stronglatest trendsstrong in web development 🚀br\nVisit our a hrefhttpswwwexamplecomnewsofficial bloga for updatesbr\nNeed help Check out the emFAQ sectionem at a hrefhttpssupportexamplecomsupportexamplecomabr\nStay inspired with daily imotivational quotesi from a hrefhttpsquotesexampleorgrandomquotesexampleorgap\n\nh3Random Tiph3\nul\n  liUse codelorem5code in VS Code to generate emlorem ipsumem text instantlyli\n  liTest links with a hrefhttpsvalidatorw3orgW3C Validatorali\nul   \n\n'

### **Chat words**

In [35]:
sample = {
    'lol' : 'laugh out loud',
    'u' : 'you',
    'wyd' : 'what are you doing',
    'gd nyt' : 'good night',
    'ilysm' : 'i love you so much',
    
}

In [36]:
def input_text(data):
    new_text = []
    for s in data.split():
        if s in sample:
            new_text.append(sample[s])
        else:
            new_text.append(s)
    return " ".join(new_text)

In [37]:
input_text('Hi today lol happen')

'Hi today laugh out loud happen'

### **Removing stop_words**

In [38]:
from nltk.corpus import stopwords


In [39]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [40]:
new_words = []

def rm_stopwords(text):
    for i in text.split():
        if i in stopwords.words('english'):
            new_words.append('')
        else:
            new_words.append(i)
    x = new_words[:]
    new_words.clear()
    return ' '.join(x)

In [41]:
rm_stopwords('hello what are you doing right now, the name of me is subham pathak')

'hello     right now,  name    subham pathak'

### **Stemming**

In [42]:
from nltk.stem.porter import PorterStemmer

In [43]:
ps = PorterStemmer()
def stemming(text):
    return ' '.join([ps.stem(word) for word in text.split()])

In [44]:
stemming('he is walking and i am running , do u know what is the difference between these two lines, if yes answer it')

'he is walk and i am run , do u know what is the differ between these two lines, if ye answer it'

### **FEATURE EXTRACTION**

In [45]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
import pandas as pd

In [46]:
df = pd.DataFrame({'text':['hi how are you', 'hi my name is subham', 'I am learning NLP from campusX', 'I am learning NLP now', 'I am a man'], 'output':[1,1,1,0,0]})
df

text  output
0                  hi how are you       1
1            hi my name is subham       1
2  I am learning NLP from campusX       1
3           I am learning NLP now       0
4                      I am a man       0

In [47]:
cv = CountVectorizer()

bow = cv.fit_transform(df['text'])


In [48]:
print(cv.vocabulary_)

{'hi': 4, 'how': 5, 'are': 1, 'you': 14, 'my': 9, 'name': 10, 'is': 6, 'subham': 13, 'am': 0, 'learning': 7, 'nlp': 11, 'from': 3, 'campusx': 2, 'now': 12, 'man': 8}


In [49]:
print(bow[0].toarray())

[[0 1 0 0 1 1 0 0 0 0 0 0 0 0 1]]


In [50]:
print(type(cv.vocabulary_))

<class 'dict'>


In [51]:
max_voc = (max(cv.vocabulary_.values()))

In [52]:
for i in range(df.shape[0]):
    print(bow[i].toarray()[0])

[0 1 0 0 1 1 0 0 0 0 0 0 0 0 1]
[0 0 0 0 1 0 1 0 0 1 1 0 0 1 0]
[1 0 1 1 0 0 0 1 0 0 0 1 0 0 0]
[1 0 0 0 0 0 0 1 0 0 0 1 1 0 0]
[1 0 0 0 0 0 0 0 1 0 0 0 0 0 0]


### **Bag of n-grams**

In [53]:
# Normal bag-of-words = n=(1,1)
# bi-grams = n=(2,2)
# tri-grams = n = (3,3)


from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(ngram_range = (2,2)) #       bi-grams

In [54]:
df

text  output
0                  hi how are you       1
1            hi my name is subham       1
2  I am learning NLP from campusX       1
3           I am learning NLP now       0
4                      I am a man       0

In [55]:
cv.fit_transform(df['text'])

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 15 stored elements and shape (5, 13)>

In [56]:
cv.vocabulary_

{'hi how': 4,
 'how are': 6,
 'are you': 2,
 'hi my': 5,
 'my name': 9,
 'name is': 10,
 'is subham': 7,
 'am learning': 0,
 'learning nlp': 8,
 'nlp from': 11,
 'from campusx': 3,
 'nlp now': 12,
 'am man': 1}

### **TF(Term Frequency)-IDF(Inverse Document frequency)**

In [57]:
df

text  output
0                  hi how are you       1
1            hi my name is subham       1
2  I am learning NLP from campusX       1
3           I am learning NLP now       0
4                      I am a man       0

In [58]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [59]:
tfid = TfidfVectorizer()

vector = tfid.fit_transform(df['text']).toarray()

print(vector.shape)

(5, 15)


In [60]:
print(tfid.idf_)
print('\n')
print(tfid.get_feature_names_out())

[1.40546511 2.09861229 2.09861229 2.09861229 1.69314718 2.09861229
 2.09861229 1.69314718 2.09861229 2.09861229 2.09861229 1.69314718
 2.09861229 2.09861229 2.09861229]


['am' 'are' 'campusx' 'from' 'hi' 'how' 'is' 'learning' 'man' 'my' 'name'
 'nlp' 'now' 'subham' 'you']
